version: '3.7'
services:
  nodejs:
    build: images/mynode
    ports:
      - "80:3000"
    depends_on:
      - mongo
      - mongo-express
    volumes:
      - type: bind
        source: ${PWD}/apps/nodeapi
        target: /app
      - /etc/localtime:/etc/localtime:ro
    networks:
      - api

  mongo:
    image: mongo
    networks:
      - api

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - api

  creationart:
    build: images/myapache
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ${PWD}/apps/creationart
        target: /var/www/html/creationart
      - /etc/localtime:/etc/localtime:ro

  phpcs-configurator:
    build: images/myimage
    volumes:
      - type: bind
        source: ${PWD}/apps/phpcs-configurator
        target: /app
      - /etc/localtime:/etc/localtime:ro

  localizer:
    build: images/myimage
    volumes:
      - type: bind
        source: ${PWD}/apps/localizer
        target: /app
      - /etc/localtime:/etc/localtime:ro

  mypsr:
    build: images/myimage
    volumes:
      - type: bind
        source: ${PWD}/apps/mypsr
        target: /app
      - /etc/localtime:/etc/localtime:ro

  fizzbuzzkata:
    build: images/myimage
    volumes:
      - type: bind
        source: ${PWD}/apps/fizzbuzzkata
        target: /app
      - /etc/localtime:/etc/localtime:ro

  my-first-ci-test:
    build: images/myimage
    volumes:
      - type: bind
        source: ${PWD}/apps/my-first-ci-test
        target: /app
      - /etc/localtime:/etc/localtime:ro

networks:
  api:
